name: karama
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1

  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.3
  # Service locator
  get_it: ^7.2.0
  # Remote API
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.4
  # Local cache
  shared_preferences: ^2.0.13
  google_fonts: ^3.0.1
  from_css_color: ^2.0.0
  font_awesome_flutter: ^10.3.0
  intl: 0.17.0
  json_path: 0.4.1
  timeago: 3.2.2
  url_launcher: 6.1.5
  page_transition: 2.0.4
  auto_size_text: 3.0.0
  smooth_page_indicator: 1.0.0+2
  flutter_svg: 0.22.0
  pin_code_fields: 7.4.0
  intl_phone_number_input: ^0.7.1
  go_router: ^6.0.0
  loading_animation_widget: ^1.2.0+4
  image_picker: ^0.8.6
  country_state_city_picker: ^1.2.8
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  flutter_hooks: ^0.18.5+1
  flutter_contacts: ^1.1.5+1
  share_plus: ^6.3.0
  change_app_package_name: ^1.1.0
  cached_network_image: ^3.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/icons/
  fonts:
    - family: 'Poppins'
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic